### ISSUE TITLE
FlexboxLayout disorder when children num  large then 16  

### ISSUE THREAD

**Issue by payallmoney** [gabdube/native-windows-gui#104] opened 2020-07-24 15:50 UTC
FlexboxLayout disorder when children num  large then 16

**Comment by gabdube** [comment] 2020-08-09 16:53
I wasn't able to reproduce this issue. See https://github.com/gabdube/native-windows-gui/blob/master/native-windows-gui/examples/flexbox_dynamic_d.rs 

Can you give me a code example?

**Comment by payallmoney** [comment] 2020-08-12 03:08
// #![windows_subsystem = "windows"] 
extern crate native_windows_gui as nwg;
extern crate native_windows_derive as nwd; 

use nwd::NwgUi;
use nwg::NativeUi;

use std::cell::RefCell;

use nwg::stretch::{geometry::{Size, Rect}, style::{Dimension as D, FlexDirection, AlignSelf}};
const FIFTY_PC: D = D::Percent(0.5);
const PT_10: D = D::Points(10.0);
const PT_5: D = D::Points(5.0);
const PT_0: D = D::Points(0.0);
const PADDING: Rect<D> = Rect{ start: PT_10, end: PT_10, top: PT_10, bottom: PT_10 };
const NOPADDING: Rect<D> = Rect{ start: PT_0, end: PT_0, top: PT_0, bottom: PT_0 };
const PADDING_5: Rect<D> = Rect{ start: PT_5, end: PT_5, top: PT_0, bottom: PT_0 };
const MARGIN: Rect<D> = Rect{ start: PT_5, end: PT_5, top: PT_5, bottom: PT_5 };
const MARGIN_5: Rect<D> = Rect{ start: PT_5, end: PT_5, top: PT_0, bottom: PT_0 };
const NOMARGIN: Rect<D> = Rect{ start: PT_0, end: PT_0, top: PT_0, bottom: PT_0 };

#[derive(Default, NwgUi)]
pub struct D2login {
    
    #[nwg_control(size:(800, 700), position:(800, 300), title: "test")]
    #[nwg_events( OnWindowClose: [D2login::exit] )]
    window: nwg::Window,
     
    #[nwg_control(parent: window,flags:"VISIBLE|BORDER" , position:(5,5),size:(790,30))]
    frame1: nwg::Frame,

    #[nwg_layout(parent: frame1,  flex_direction: FlexDirection::Row,padding: NOPADDING )]
    layout1: nwg::FlexboxLayout,
 
    #[nwg_control(parent: frame1,text: "1:")]
    #[nwg_layout_item(layout: layout1,size: Size { width:D::Points(70.0), height: D::Points(35.0)})]
    label1: nwg::Label,  
    #[nwg_control(parent: frame1,text: "2")]
    #[nwg_layout_item(layout: layout1 ,size: Size { width:D::Points(85.0), height: D::Points(30.0)},align_self: AlignSelf::FlexEnd,)]
    check01: nwg::Label,
    #[nwg_control(parent: frame1,text: "3")]
    #[nwg_layout_item(layout: layout1 ,size: Size { width:D::Points(85.0), height: D::Points(30.0)},align_self: AlignSelf::FlexEnd,)]
    check02: nwg::Label,
    #[nwg_control(parent: frame1,text: "4")]
    #[nwg_layout_item(layout: layout1 ,size: Size { width:D::Points(85.0), height: D::Points(30.0)},align_self: AlignSelf::FlexEnd,)]
    check03: nwg::Label,
    #[nwg_control(parent: frame1,text: "5")]
    #[nwg_layout_item(layout: layout1 ,size: Size { width:D::Points(85.0), height: D::Points(30.0)},align_self: AlignSelf::FlexEnd,)]
    check04: nwg::Label,
    #[nwg_control(parent: frame1,text: "6")]
    #[nwg_layout_item(layout: layout1 ,size: Size { width:D::Points(85.0), height: D::Points(30.0)},align_self: AlignSelf::FlexEnd,)]
    check05: nwg::Label,

    #[nwg_control(parent: frame1,text: "7")]
    #[nwg_layout_item(layout: layout1,size: Size { width:D::Points(80.0), height: D::Points(30.0)},align_self: AlignSelf::FlexEnd, )]
    #[nwg_events( OnButtonClick: [D2login::add_message] )]
    item_btn: nwg::Button,

    #[nwg_control(parent: frame1,text: "8")]
    #[nwg_layout_item(layout: layout1,size: Size { width:D::Points(80.0), height: D::Points(30.0)},align_self: AlignSelf::FlexEnd, )]
    #[nwg_events( OnButtonClick: [D2login::add_message] )]
    btn1: nwg::Button,

    #[nwg_control(parent: window,flags:"VISIBLE|BORDER" , position:(5,50),size:(790,30))]
    frame2: nwg::Frame,

    #[nwg_layout(parent: frame2, flex_direction: FlexDirection::Row,padding: NOPADDING)]
    layout2: nwg::FlexboxLayout,
 
    #[nwg_control(parent: frame2,text: "9:")]
    #[nwg_layout_item(layout: layout2 ,size: Size { width:D::Points(70.0), height: D::Points(30.0)},align_self: AlignSelf::FlexEnd,)]
    label2: nwg::Label, 
    
    #[nwg_control(parent: frame2,size:(100,20))]
    #[nwg_layout_item(layout: layout2 ,size: Size { width:D::Points(20.0), height: D::Points(30.0)},align_self: AlignSelf::FlexEnd,)]
    account: nwg::TextInput,

    #[nwg_control(parent: frame2,text: "10")]
    #[nwg_layout_item(layout: layout2 ,size: Size { width:D::Points(20.0), height: D::Points(30.0)},align_self: AlignSelf::FlexEnd,)]
    check06: nwg::Label,
    #[nwg_control(parent: frame2,text: "11")]
    #[nwg_layout_item(layout: layout2 ,size: Size { width:D::Points(20.0), height: D::Points(30.0)},align_self: AlignSelf::FlexEnd,)]
    check07: nwg::Label,
    #[nwg_control(parent: frame2,text: "12")]
    #[nwg_layout_item(layout: layout2 ,size: Size { width:D::Points(85.0), height: D::Points(30.0)},align_self: AlignSelf::FlexEnd,)]
    check08: nwg::Label,
    #[nwg_control(parent: frame2,text: "13")]
    #[nwg_layout_item(layout: layout2 ,size: Size { width:D::Points(115.0), height: D::Points(30.0)},align_self: AlignSelf::FlexEnd,)]
    check09: nwg::Label,
    #[nwg_control(parent: frame2,text: "14")]
    #[nwg_layout_item(layout: layout2 ,size: Size { width:D::Points(75.0), height: D::Points(30.0)},align_self: AlignSelf::FlexEnd,)]
    check10: nwg::Label,
    #[nwg_control(parent: frame2,text: "15")]
    #[nwg_layout_item(layout: layout2 ,size: Size { width:D::Points(50.0), height: D::Points(30.0)},align_self: AlignSelf::FlexEnd,)]
    check11: nwg::Label, 

    #[nwg_control(parent: frame2,text: "16")]
    #[nwg_layout_item(layout: layout2 ,size: Size { width:D::Points(50.0), height: D::Points(30.0)},align_self: AlignSelf::FlexEnd,)]
    check12: nwg::Label, 

    #[nwg_control(parent: frame2,text: "17")]
    #[nwg_layout_item(layout: layout2 ,size: Size { width:D::Points(50.0), height: D::Points(30.0)},align_self: AlignSelf::FlexEnd,)]
    check13: nwg::Label, 

    buttons: RefCell<Vec<nwg::Button>>,
    handlers: RefCell<Vec<nwg::EventHandler>>,
    tab1: RefCell<nwg::Tab>,  
    test_button: RefCell<nwg::Button>,
    test_button1: RefCell<nwg::Button>,
    test_checkbox1: RefCell<nwg::CheckBox>,
}

impl D2login {

    fn add_message(&self) { 
    }

    fn exit(&self) {
        let handlers = self.handlers.borrow();
        for handler in handlers.iter() {
            nwg::unbind_event_handler(&handler);
        }
        
        nwg::stop_thread_dispatch();
    } 

}

fn main() {
    nwg::init().expect("Failed to init Native Windows GUI");
    // nwg::Font::set_global_family("Microsoft YaHei").expect("Failed to set default font");
    let mut _ui = D2login::build_ui(Default::default()).expect("Failed to build UI"); 

    nwg::dispatch_thread_events();
}

**Comment by gabdube** [comment] 2020-08-14 18:30
Hmm looks like specifying a parent in the derive breaks the order. I'll try to fix this today or tomorrow.

**Comment by gabdube** [comment] 2020-08-14 19:00
Should be fixed now. Just update `native-windows-derive` to `1.0.1`

**Comment by payallmoney** [comment] 2020-08-15 03:33
> Should be fixed now. Just update `native-windows-derive` to `1.0.1`

Yes , it's fixed . Thanks for your work.

**Closed** 2020-08-15 03:58 UTC
