### ISSUE TITLE
ComboBox vertical alignment seems off in FlexboxLayout

### ISSUE THREAD

**Issue by RustyJoeM** [gabdube/native-windows-gui#136] opened 2020-10-20 08:23 UTC
Hello,

i'm using FlexboxLayout across the app, and i stumbled upon issue with aligning the label with "dropdowns" - ComboBox<> elements...

Common alignment seems to work fine for labels, text inputs, buttons, but when i have dropdown on "line"  of various elements, i'm unable to get it right (centered, or baselined) with the rest of elements.

Pseudo-code: (should be copy-able into raw/empty app template):

```rust
fn supported_langs() -> Vec<String> {
    vec!["English".to_string(), "Česky".to_string(), "русский".to_string()]
}

const SIZE: Size<Dimension> = Size { width: Dimension::Percent(0.25), height: Dimension::Points(40.0) };


**** UI elements: ****
    #[nwg_control(title: "misaligned combobox", size: (360, 240), position: (80, 60))]
    #[nwg_events(OnWindowClose: [FillerApp::exit(SELF)])]
    window: nwg::Window,

    #[nwg_layout(parent: window, flex_direction: FlexDirection::Row, align_items: AlignItems::Center)]
    main_layout: nwg::FlexboxLayout,

    #[nwg_control(text: "\u{2328}:", h_align: HTextAlign::Right)]
    #[nwg_layout_item(layout: main_layout, size: SIZE)]
    lang_label: nwg::Label,

    #[nwg_control(collection: supported_langs(), selected_index: Some(0))]
    #[nwg_layout_item(layout: main_layout, size: SIZE)]
    lang_dropdown: nwg::ComboBox<String>,
    
    #[nwg_control(text: "Value separator:", h_align: HTextAlign::Right)]
    #[nwg_layout_item(layout: main_layout, size: SIZE)]
    separator_label: nwg::Label,

    #[nwg_control(text: ";")]
    #[nwg_layout_item(layout: main_layout, size: SIZE)]
    separator_input: nwg::TextInput,
```

**Comment by gabdube** [comment] 2020-10-20 16:47
I'll see what I can find. The combobox has a rendering hack, so it's probably messing with the layout.

**Comment by RustyJoeM** [comment] 2020-10-20 16:54
thank you!

Not sure if it helps, but, i tested a workaround

 - adding a wrapping nwg::Frame over the ComboBox<> wrapper frame,
 - align_items: AlignItems::Center for the layout of wrapper frame

seems to align resulting set properly...

**Comment by RicoRodriges** [comment] 2020-10-30 06:47
Layout works perfect. The problem is `ComboBox<>` control has system height based on fonts. See the picture

![image](https://user-images.githubusercontent.com/20505625/97669095-6ceebf80-1a94-11eb-8728-74b9215ea5a7.png)

`SetWindowPos` for comboboxes works not as other controls.

**Comment by gabdube** [comment] 2021-01-26 00:23
well... better late than never. I added a `v_align` parameter to the combobox to change the vertical alignment. It now defaults to center instead of top, just like the other controls. It will be in 1.0.9, which I am about to release.

**Closed by gabdube** 2021-01-26 00:23 UTC
